name = "hex-rcf"
defaultTargets = ["HexRCF"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "v0.8.0"

[[require]]
name = "HexPolyZ"
git = "https://github.com/leanprover/hex-poly-z.git"
rev = "v0.8.0"

[[require]]
name = "HexPolyZMathlib"
git = "https://github.com/leanprover/hex-poly-z-mathlib.git"
rev = "v0.8.0"

[[require]]
name = "HexRealRoots"
git = "https://github.com/leanprover/hex-real-roots.git"
rev = "v0.8.0"

[[require]]
name = "HexRealRootsMathlib"
git = "https://github.com/leanprover/hex-real-roots-mathlib.git"
rev = "v0.8.0"

[[require]]
name = "TauCeti"
git = "https://github.com/TauCetiProject/TauCeti.git"
rev = "1c497c347f615b3087cb605f8cf743e591376105"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "6b7abb3c7686292736be2955bd3eb9ebf63b456a"

[[lean_lib]]
name = "HexRCF"

[[lean_lib]]
name = "HexRCFTests"
globs = ["HexRCF.LanguageTests", "HexRCF.SturmBuilderTests", "HexRCF.CarrierTests", "HexRCF.IsolationsTests", "HexRCF.SeparationTests", "HexRCF.CellsTests", "HexRCF.CommonRootTests", "HexRCF.SignMatrixTests", "HexRCF.BuilderTests", "HexRCF.CertificateTests", "HexRCF.DecisionTests", "HexRCF.ReifyTests", "HexRCF.HandlerTests.Support", "HexRCF.HandlerTests.Async", "HexRCF.HandlerTests", "HexRCF.LintTests"]
