name = "hex-rcf"
defaultTargets = ["HexRCF"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexRealRoots"
git = "https://github.com/leanprover/hex-real-roots.git"
rev = "5ea6914dc230e7519722d237b46e02ec6e5ff2d0"

[[require]]
name = "HexRealRootsMathlib"
git = "https://github.com/leanprover/hex-real-roots-mathlib.git"
rev = "3634195024275435520c6b6d106f371f5c45df67"

[[require]]
name = "HexPolyZ"
git = "https://github.com/leanprover/hex-poly-z.git"
rev = "385df1df6b2667aeb001b6b781f7109943de243b"

[[require]]
name = "HexPolyZMathlib"
git = "https://github.com/leanprover/hex-poly-z-mathlib.git"
rev = "db6441e818dd3a21e99bd7bf7a1b53291a140207"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "a47240943e925951a676d1a1c2f2a615ae68fdef"

[[lean_lib]]
name = "HexRCF"

[[lean_lib]]
name = "HexRCFTests"
globs = [
  "HexRCF.LanguageTests",
  "HexRCF.SturmBuilderTests",
  "HexRCF.CarrierTests",
  "HexRCF.IsolationsTests",
  "HexRCF.SeparationTests",
  "HexRCF.CellsTests",
  "HexRCF.CommonRootTests",
  "HexRCF.SignMatrixTests",
  "HexRCF.BuilderTests",
  "HexRCF.CertificateTests",
  "HexRCF.DecisionTests",
  "HexRCF.ReifyTests",
  "HexRCF.LintTests",
]
